fix broken expression matching (closes #288)
stfc/fparser pull request #289
Opened 2021-01-19 01:58 UTC by rupertford

2021-01-19 16:38 UTC, rupertford commented
Ready for first review from @arporter

2021-01-20 09:12 UTC, arporter requested changes
I have to say I'm in two minds about this. It does fix the problem and this version can now parse all of NEMO again. However, I'm not that comfortable with the fact that we now have `Add_Operand` as an operand of operators other than `+/-`. I suppose it's an improvement over the spurious Structure_Constructor_2 instances we used to get in the parse tree. Given that master is currently broken, we could go with this approach and open an issue to deal with the problem more robustly. I did think that one solution would be to do something similar to what is done for strings (and parentheses?) and replace all literals with exponents with a temporary symbol before doing any matching. (The `repmap` type functionality.)

Tests are all OK.
Updated documentation builds fine.
Changes are pylint/pycodestyle clean.
There are just a few minor comments in-line.

2021-01-20 15:05 UTC, rupertford commented on doc/developers_guide.rst
> +To solve the problem for thie specific case fparser2 includes
oops.

2021-01-20 15:05 UTC, rupertford commented on doc/developers_guide.rst
> +matching of a Level2 expression::
updated

2021-01-20 15:05 UTC, rupertford commented on doc/developers_guide.rst
> +As expected, this would fail to match, due to the level2 expression
modified

2021-01-20 15:06 UTC, rupertford commented on src/fparser/two/Fortran2003.py
> +    Rule R705 in implemented in two parts, the first with the optional
oops.

2021-01-20 15:20 UTC, rupertford commented on src/fparser/two/Fortran2003.py
>          return BinaryOpBase.match(
oops.

2021-01-20 15:22 UTC, rupertford commented on src/fparser/two/tests/fortran2003/test_add_operand_r705.py
> +
I like blank lines after doc strings :-P

2021-01-20 15:22 UTC, rupertford commented on src/fparser/two/tests/fortran2003/test_add_operand_r705.py
> +
Boo.

2021-01-20 15:27 UTC, rupertford commented on src/fparser/two/tests/fortran2003/test_add_operand_r705.py
> +    ("a * b", "Add_Operand(Name('a'), '*', Name('b'))"),
I'm not sure what you mean. Could you please explain. Sorry.

2021-01-20 15:28 UTC, rupertford commented on src/fparser/two/tests/fortran2003/test_add_operand_r705.py
> +    '''Test that the level_2_exp class match allows a "+" or "-" operator
oops

2021-01-20 15:29 UTC, rupertford commented on src/fparser/two/tests/test_fortran2003.py
>      assert str(obj) == '0.0E-1'
It is already 2021 :-)

2021-01-20 16:18 UTC, rupertford commented
After discussion with @arporter we have decided to go with the solution in this PR for the moment but to raise another issue to fix the problem in a nicer way, see issue #290.

Ready for next review.

2021-01-20 16:22 UTC, arporter commented on src/fparser/two/tests/fortran2003/test_add_operand_r705.py
> +    ("a * b", "Add_Operand(Name('a'), '*', Name('b'))"),
It's OK - I was worried this might break the PSyIR fparser2 frontend but I've tested and it's fine.

2021-01-20 16:25 UTC, arporter commented on src/fparser/two/tests/fortran2003/test_add_operand_r705.py
> +
You're allowed them inside :-) (Although I think it's overkill for tests personally.)

2021-01-20 16:27 UTC, arporter approved these changes
All requested changes have been made and #290 has been opened.
Doc still builds fine.
All tests still pass with 100% diff coverage.

2021-01-20 16:37 UTC, merged