Remove last traces of python 2 special handling
stfc/fparser pull request #328
Opened 2022-04-06 16:57 UTC by ZedThree

PR into #322 removing last few bits of `six` and python 2 special handling

2022-05-10 07:29 UTC, arporter commented
Hi @ZedThree, if you could fix the conflicts on this one and then I'll review it... Thanks :-)

2022-05-10 13:03 UTC, ZedThree commented
@arporter Good to go :)

2022-05-10 14:14 UTC, arporter requested changes
Many thanks for taking this on Peter - it's a big improvement.
GHA and coverage is all fine.
Documentation builds and looks fine.
There's one method that still talks quite a lot about Py2 and Py3.
There's also one test that you've removed completely and I'm not sure why.
Apart from that, there are just a few places where I've taken the opportunity to ask for fixes to associated pylint warnings. (I tried to keep this to a minimum because otherwise you'd be here all year given the state of some of the existing code.)

2022-05-10 14:46 UTC, ZedThree commented on src/fparser/common/tests/test_readfortran.py
> +    :type include_info: list of str
Sure, will do. Future project might be to migrate to type hinting?

2022-05-10 14:47 UTC, ZedThree commented on src/fparser/two/tests/fortran2003/test_entity_decl_r504.py
> -def test_entity_decl_repr():
Oops, sorry, moving too fast! Will revert!

2022-05-10 15:17 UTC, ZedThree commented on src/fparser/common/base_classes.py
> +        dims = [tuple(map(str.strip, dim)) for dim in dims]
I've now done this for all files in `common` and `two` that matched the regexp `^\ {4,8}return$` and then manual checking

2022-05-10 15:25 UTC, ZedThree commented
One other change that I've not done but just seen is use of `match = staticmethod(match)` which could be converted to be a decorator on the method instead. This is a pretty mechanical fix (just taken me a couple of seconds to do with an Emacs macro), would you like that in here too? That's 135 lines

2022-05-11 08:38 UTC, arporter commented
Hi @ZedThree, is this ready for review again?

2022-05-11 08:50 UTC, arporter commented on src/fparser/common/tests/test_readfortran.py
> +    :type include_info: list of str
Yes, ultimately that would be good.

2022-05-11 11:51 UTC, arporter commented on src/fparser/two/Fortran2003.py
> -        return
return None pls.

2022-05-11 11:51 UTC, arporter commented on src/fparser/two/Fortran2003.py
> -        return
`return None` please.

2022-05-11 11:52 UTC, arporter commented on src/fparser/two/Fortran2003.py
> -        return
`return None`

2022-05-11 12:09 UTC, ZedThree commented on src/fparser/common/utils.py
Sure, will do. To be clear, this is equivalent, but I agree that `return None` is more explicit :+1:

2022-05-11 12:09 UTC, arporter requested changes
Almost there apart from those places where a `return None` is needed :-)
Please note that our way of working on GitHub is for the reviewer to mark conversations as 'resolved' as that makes it easier for them to ensure that each has been done to their satisfaction.

2022-05-11 12:09 UTC, arporter commented on src/fparser/two/utils.py
> -        return
return None pls.

2022-05-11 12:09 UTC, arporter commented on src/fparser/two/utils.py
>                  "Supplied pattern should be a list, tuple, str or regular "
Our standard is to prefix all of the sub-strings with `f` for consistency.

2022-05-11 12:15 UTC, ZedThree commented on src/fparser/common/base_classes.py
> +        pass
True, but `pass` is probably more explicit that the method hasn't been implemented? Or perhaps even `raise NotImplementedError` if you want to ensure subclasses implement it

2022-05-11 12:15 UTC, ZedThree commented on src/fparser/common/base_classes.py
> -        return
`self.handle_unknown_item` will unconditionally raise an exception

2022-05-16 12:10 UTC, arporter commented on src/fparser/common/base_classes.py
> +        pass
On coming back to this I think `return None` is the appropriate thing to do - this then lines up with the docstring.

2022-05-16 12:11 UTC, arporter commented on src/fparser/common/base_classes.py
> -        return
Aha. Please could you add a comment to that effect before `self.handle_unknown_item(item)`.

2022-05-16 13:13 UTC, ZedThree commented on src/fparser/common/base_classes.py
> -        return
Maybe instead we change the function name to `raise_unknown_item_error` or similar?

2022-05-16 14:38 UTC, arporter commented on src/fparser/common/base_classes.py
> +        pass
Please could you change this to `return None`.

2022-05-19 15:36 UTC, arporter approved these changes
All good now thanks. Will proceed to merge once CI is complete (and happy).

2022-05-19 15:40 UTC, arporter commented
The missed lines are all statements where `return` has been replaced by `return None` in `Fortran2003.py`. These weren't covered previously and I'm not going to insist they be covered now.

2022-05-19 15:40 UTC, merged