Fix parsing of format-items with hollerith items and omitted commas
stfc/fparser pull request #364
Opened 2022-08-02 18:47 UTC by CoderPuppy

This fixes parsing of hollerith items in `format-items` in three cases:
- Omitted comma before a hollerith item: `/3Habc`
- Omitted comma after a hollerith item: `3Habc/`
- Trailing whitespace in trailing hollerith item: `4Hspc `

It also changes `Format_Item_List` to match single item lists rather than bail out and rely on `Format_Item`. This matches the behavior of `SequenceBase` and all the generated lists.

2022-08-03 08:43 UTC, arporter commented
Thanks very much for this @CoderPuppy. Are you happy to tackle the missing coverage or would you like someone else to take it from here?

2022-08-09 08:36 UTC, arporter requested changes
Changes look good and are well commented (thanks).
I have a question about one changed line and there is some minor tidying to do for pylint in the new tests.
Once that's sorted, this can be merged.
There's no need for a documentation update.

2022-08-09 08:36 UTC, arporter commented on src/fparser/two/Fortran2003.py
> +                item_list.append(Hollerith_Item(current_string[:num_chars]))
Please could you explain the reason for this change?

2022-08-09 08:36 UTC, arporter commented on src/fparser/two/tests/fortran2003/test_format_item_list.py
> +    from fparser.two import utils
Please could you move this import up to the top and replace the use of `format` with f-strings in the new tests (as suggested by pylint).

2022-08-09 08:36 UTC, arporter commented on src/fparser/two/tests/fortran2003/test_format_item_list.py
> +    from fparser.two import utils
Please rm this import.

2022-08-09 08:36 UTC, arporter commented on src/fparser/two/tests/fortran2003/test_format_item_list.py
> +    from fparser.two import utils
Please rm this import.

2022-08-09 14:31 UTC, CoderPuppy commented
I have a related change to `BracketBase`, preventing the loss of trailing spaces. Should I add that here or create another PR?

2022-08-10 08:24 UTC, arporter commented on src/fparser/two/Fortran2003.py
> +                item_list.append(Hollerith_Item(current_string[:num_chars]))
Thanks.

2022-08-10 08:25 UTC, arporter commented
> I have a related change to BracketBase, preventing the loss of trailing spaces. Should I add that here or create another PR?

A new PR would be great thanks.

2022-08-10 12:57 UTC, arporter requested changes
All requested changes have been made.
However, I see CodeCov is reporting a change in coverage which I think is L9094 ( https://app.codecov.io/gh/stfc/fparser/compare/364/changes#D1L9094) in Fortran2003.py (the Format_Item_C1002). Hopefully this just needs a tweak to one of the tests.
Are you OK to take a look at that?

2022-08-10 13:30 UTC, CoderPuppy commented
That code is actually redundant now because I implemented slash and comma descriptors in `Format_Item_List`. It can only be triggered by directly calling `Format_Item` or `Format_Item_C1002`. I left it behind to avoid breaking stuff unnecessarily.

It is covered now, but this new test and a few old tests are testing things which shouldn't be able to occur (because standard usage of `Format_Item_C1002` goes through `Format_Item_List`).

2022-08-11 07:32 UTC, arporter approved these changes
All requested changes have been made.
Coverage is now great.
Will proceed to merge.

2022-08-11 07:33 UTC, merged