Add support for visiting tuples in walk() utility
stfc/fparser pull request #368
Opened 2022-08-04 15:55 UTC by antoine-morvan

Hello, 

This PR addresses issue https://github.com/stfc/fparser/issues/367

I am not familiar with Python unit testing yet, thus did not add a test. Hope this is not too far off coding policies ^^'

Best.

2022-08-08 10:02 UTC, arporter commented
Thanks @antoine-morvan, the fix looks good. Although codecov reports that it is covered by existing tests, I think it would be good to add a new, explicit test based on your reproducer. Would you like me to do that?

2022-08-08 10:17 UTC, antoine-morvan commented
> Thanks @antoine-morvan, the fix looks good. Although codecov reports that it is covered by existing tests, I think it would be good to add a new, explicit test based on your reproducer. Would you like me to do that?

I will try to add one, that will be a good exercise before setting up tests in my code base :)

2022-08-09 08:01 UTC, arporter requested changes
Almost there now.
Only issue is the location of the new test (which is my fault because I didn't say where to put it).
Would you mind moving it into the `fparser/src/fparser/two/tests/utils/test_walk.py` file and removing the `test_issue367.py` file. (We inherited that way of naming test files when we took on fparser but have subsequently moved to structuring the tests to reflect the code structure.)

2022-08-11 07:43 UTC, arporter requested changes
A couple of minor things need fixing and then we should be OK.

2022-08-11 07:43 UTC, arporter commented on src/fparser/two/tests/utils/test_walk.py
> +def test_reproduce_issue367():
Please could you rename this test to something like `test_walk_tuple` and add a brief doc string to the test.
This file also has a couple of Black formatting errors.
Once that's done we really should be ready to go :-)

2022-08-11 08:13 UTC, antoine-morvan commented
Should be better now :)

2022-08-11 08:37 UTC, arporter approved these changes
All requested changes have been made (thanks).
Black is happy and coverage is good.
Will proceed to merge.

2022-08-11 08:37 UTC, merged