(Closes #432) add RTD yaml
stfc/fparser pull request #439
Opened 2024-01-04 10:22 UTC by arporter

Fixes issues with RTD build of docs by adding a yaml config. file.

2024-01-04 10:42 UTC, arporter commented
(I found that if I removed `doc/source/autoapi` then my local build of the docs also succeeds.)

2024-01-04 10:46 UTC, arporter commented
It turns out that the `Makefile` already has a `cleanall` target that does this but the message it printed was misleading - I've improved it.

This is now ready for review - it does just simply add a configuration file for the RTD build.

2024-01-05 10:57 UTC, sergisiso requested changes
@arporter See comment inline

2024-01-05 10:57 UTC, sergisiso commented on .readthedocs.yaml
> +     - requirements: doc/pip_requirements.txt
The rest of the PR looks good, but I am just wondering about this line.

At least all the dependencies listed on doc/pip_requirements.txt should also be in the extras_require doc section of the setup.cfg since in the local environment I would expect `pip install -e .[doc]` to install everything.

But then, is this duplication necessary? Wouldn't the readthedocs just work fine without this line and file if all the dependencies are properly listed in the setup.cfg configuration?

And finally, (maybe not this PR but since we are at it) why do we still have a setup.cfg if we already have a pyproject.toml. I thought this file was to centralise all the configurations as shown in https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html

2024-01-10 10:06 UTC, arporter commented on .readthedocs.yaml
> +     - requirements: doc/pip_requirements.txt
I think I must have only added the bare minimum to get setuptools_scm working. I've migrated the rest of setup.cfg over to it now and removed that file.

2024-01-10 10:50 UTC, arporter commented on .readthedocs.yaml
> +     - requirements: doc/pip_requirements.txt
I've also now removed pip_requirements (and moved the packages it listed under the `doc` target in pyproject.toml). The docs still build fine.

2024-01-10 10:53 UTC, arporter commented
Things are much better now (I think). Ready for another look.

2024-01-11 13:00 UTC, sergisiso approved these changes
@arporter Thanks for moving all configuration to pyproject, the PR looks good now. I will check after merging that the RTD is properly updated.

2024-01-11 13:05 UTC, merged